language: cpp

compiler:
  - gcc-4.8
  - clang

cache: apt

before_install:
  - sudo apt-get update
  - sudo apt-get install g++-4.8 pkg-config libfltk1.3-dev libglew-dev libcurl3-openssl-dev libjpeg-dev libxinerama-dev libxft-dev
  - hg clone http://hg.libsdl.org/SDL && cd SDL && ./configure && make && sudo make install && cd ..
  - curl https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz | tar -xz && cd SDL2_image-2.0.0 && ./configure && make && sudo make install && cd ..

script: cmake CMakeLists.txt && make


